class config:
    DEFAULT_MIN_OCCURENCES = 50
    BATCH_SIZE = 10
    READER_NUM_PARALLEL_BATCHES = 1
    NUM_TRAIN_EPOCHS = 2
    SHUFFLE_BUFFER_SIZE = 10000
    CODE2VEC_VOCABS_PATH = ""
    VEC_TRAINING_FREQ_DICTS_PATH = "dataset/j-med/java-med.vec.c2v.dict"
    VAR_TRAINING_FREQ_DICTS_PATH = "dataset/java-small/java-small.var.c2v.dict"
    CREATE_VOCAB = True
    DEFAULT_INT32_LOOKUP_VALUE = 0
    DEFAULT_STRING_LOOKUP_VALUE = "None"
    MAX_NUMBER_OF_WORDS_IN_FREQ_DICT = 10000000
    MAX_CONTEXTS = 300
    TARGET_VOCAB_SIZE = 35451
    TOKEN_EMBED_DIMENSION = 100
    PATH_EMBED_DIMENSION = 100
    DROPOUT_KEEP_RATE = 0.75
    VALIDATION_SIZE = 8192
    TEST_SIZE = 0
    NUMBER_OF_PREDICTIONS = 5

    VEC_NET_TOKEN_SIZE = 3610
    VEC_NET_PATH_SIZE = 1468667
    VEC_NET_TARGET_SIZE = 3212

    VAR_NET_TOKEN_SIZE = 440
    VAR_NET_PATH_SIZE = 312188
    VAR_NET_TARGET_SIZE = 679
