
class config:
    CODE2VEC_VOCABS_PATH = ""
    TRAINING_FREQ_DICTS_PATH = ""
    CREATE_VOCAB = True
    DEFAULT_INT32_LOOKUP_VALUE = -1
    DEFAULT_STRING_LOOKUP_VALUE = "None"
    MAX_NUMBER_OF_WORDS_IN_FREQ_DICT = 1301136