class config:
    BATCH_SIZE = 64
    READER_NUM_PARALLEL_BATCHES = 1
    NUM_TRAIN_EPOCHS = 2
    SHUFFLE_BUFFER_SIZE = 10000
    CODE2VEC_VOCABS_PATH = ""
    TRAINING_FREQ_DICTS_PATH = ""
    CREATE_VOCAB = True
    DEFAULT_INT32_LOOKUP_VALUE = 0
    DEFAULT_STRING_LOOKUP_VALUE = "None"
    MAX_NUMBER_OF_WORDS_IN_FREQ_DICT = 350000
    MAX_CONTEXTS = 300
    TARGET_VOCAB_SIZE = 35451
    TOKEN_EMBED_DIMENSION = 100
    PATH_EMBED_DIMENSION = 200
    DROPOUT_KEEP_RATE = 0.75
    VALIDATION_SIZE = 1024
    TEST_SIZE = 16384

    NET_TOKEN_SIZE = 390340
    NET_PATH_SIZE = 390340
    NET_TARGET_SIZE = 653